backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Post", name: "featuredpost", widget: "boolean" }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page"
            }
          - { label: Title, name: title, widget: string }
          - { label: Heading, name: heading, widget: string }
          - { label: Info Title, name: info1, widget: string }
          - { label: Info subTitle, name: infoSubTitle, widget: string }
          - { label: Product Hero Image, name: productHeroImage, widget: image }
          - { label: Subheading, name: subheading, widget: string }
          - {
              label: "Slider Images",
              name: "sliderImages",
              widget: "list",
              fields: [
                { label: "Image", name: "url", widget: "image" },
                { label: "Alt Text", name: "alt", widget: "string" }
              ]
            }
          - {
              label: "Categories",
              name: "categories",
              widget: "list",
              fields: [
                { label: "ID", name: "id", widget: "string" },
                { label: "Title", name: "title", widget: "string" },
                { label: "Image", name: "image", widget: "image" },
                { label: "Description", name: "description", widget: "text", required: false }
              ]
            }
          - {
              label: "Testimonials",
              name: "testimonials",
              widget: "list",
              fields: [
                { label: "User Name", name: "userName", widget: "string" },
                { label: "Voice of Customer", name: "voc", widget: "text" },
                 { label: "Rating", name: "rating", widget: "number" }

              ]
            }
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: Ahout us Image, name: aboutUsLanding, widget: image }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/products/index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "product-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Heading, name: heading, widget: string }
          - { label: Description, name: description, widget: string }
          - {
              label: Intro,
              name: intro,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Blurbs,
                    name: blurbs,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Text, name: text, widget: text },
                      ],
                  },
                ],
            }
          - {
              label: Main,
              name: main,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Image1,
                    name: image1,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image2,
                    name: image2,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image3,
                    name: image3,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                ],
            }
          - {
              label: Testimonials,
              name: testimonials,
              widget: list,
              fields:
                [
                  { label: Quote, name: quote, widget: string },
                  { label: Author, name: author, widget: string },
                ],
            }
          - { label: Full_image, name: full_image, widget: image }
          - {
              label: Pricing,
              name: pricing,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: string },
                  {
                    label: Plans,
                    name: plans,
                    widget: list,
                    fields:
                      [
                        { label: Plan, name: plan, widget: string },
                        { label: Price, name: price, widget: string },
                        {
                          label: Description,
                          name: description,
                          widget: string,
                        },
                        { label: Items, name: items, widget: list },
                      ],
                  },
                ],
            }
      - file: "src/pages/policies/index.md"
        label: "Policies Page"
        name: "policies"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "policies-page"
            }
          - { label: "Description", name: "description", widget: "text" }
          - {
              label: "Policies",
              name: "policies",
              widget: "list",
              fields: [
                { label: "ID", name: "id", widget: "string" },
                { label: "Title", name: "title", widget: "string" },
                {
                  label: "Content",
                  name: "content",
                  widget: "object",
                  fields: [
                    { label: "Main Text", name: "mainText", widget: "text" },
                    {
                      label: "Sub Sections",
                      name: "subSections",
                      widget: "list",
                      fields: [
                        { label: "Title", name: "title", widget: "string" },
                        { label: "Items", name: "items", widget: "list" }
                      ]
                    }
                  ]
                }
              ]
            }